#!/bin/bash

### BEGIN INIT INFO 
# Provides: kni 
# Required-Start: $local_fs $network $syslog 
# Required-Stop: 
# Default-Start: 2 3 4 5 
# Default-Stop: 0 1 6 
# Short-Description: Start KNI - Kiosk Network Identification 
# Description: The KNI service enable network query
### END INIT INFO

# Check if the user is root
if [[ $EUID -ne 0 ]]; then
   echo "This script must be executed by root" 1>&2
   exit 1
fi

# Load service functions
. /lib/lsb/init-functions

case "$1" in
start)
    log_begin_msg "Starting KNI - Kiosk Network Identification"
    value=`pgrep -f 'nc -l -v 55555'; echo $?`
    if [ "$value" -ne 0 ]
    then
        /sbin/runuser -l usuario -c 'while true; do printf "Kiosk in `hostname`" | nc -l -v 55555; sleep 0.05s; done' >> /var/log/kni.log 2>&1 &
        log_end_msg $?
    else
        log_end_msg 1
        exit 1
    fi
    ;;
stop)
    log_begin_msg "Stoping KNI - Kiosk Network Identification"
    pids=`pgrep -f 'nc -l -v 55555'`
    if [ -n "$pids" ]
    then
        for i in $pids
        do
            kill -9 $i
        done
    fi
    log_end_msg 0
    ;;
*)
    echo "Use: $0 (start | stop)"
esac
