#!/bin/sh

set -e

lb config noauto \
	--apt apt \
	--apt-ftp-proxy $http_proxy \
	--apt-http-proxy $http_proxy \
	--apt-indices none \
	--architectures amd64 \
	--binary-images iso-hybrid \
	--bootappend-live "boot=live components username=usuario live-config.user-default-groups=audio,video,usuario locales=en_US.UTF-8 keyboard-layouts=br keyboard-model=pc105" \
	--debian-installer live \
	--debian-installer-gui false \
	--debian-installer-preseedfile $di_preseed
	--distribution stretch \
	--iso-application "The Basic (Micro) Kiosk" \
	--iso-preparer "Micro Kiosk v0.0.1" \
	--iso-publisher "Micro Kiosk project; https://github.com/angalq/microkiosk" \
	--iso-volume "Micro Kiosk 201905" \
	--mode debian \
	--system live \
	--verbose \
	--win32-loader false
	"${@}"
