#!/bin/sh

set -e

lb config noauto \
	--apt apt \
	--apt-ftp-proxy $http_proxy \
	--apt-http-proxy $http_proxy \
	--apt-indices true \
	--architectures amd64 \
	--binary-images iso-hybrid \
	--bootappend-live "boot=live components username=usuario live-config.user-default-groups=audio,video,usuario locales=en_US.UTF-8 keyboard-layouts=br keyboard-model=pc105" \
	--debian-installer live \
	--debian-installer-gui false \
	--distribution stretch \
	--mode debian \
	"${@}"
