#!/bin/sh

set -e

lb config noauto \
	--apt apt \
	--apt-ftp-proxy $http_proxy \
	--apt-http-proxy $http_proxy \
	--apt-indices true \
	--architectures amd64 \
	--binary-images iso-hybrid \
	# --debian-installer false \
	--debian-installer-gui false \
	--distribution stretch \
	--initramfs none \
	--mode debian \
	--system normal \
	"${@}"
